
title: Modeling Language Engineering and Execution (MLE) workshop
email: mle@inria.fr
description: >- # this means to ignore newlines until "baseurl:"
  The Modeling Language Engineering and Execution (MLE) workshop
  aims at bringing together researchers and practitioners 
  working on modeling language engineering.
  It is a meeting opportunity for Software Language Engineering (SLE) enthusiasts
  within the software modeling community.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mleworkshop.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - bundle
  - _site
